import type { Template, TemplateSectionSpec, TemplateEntityTypeSpec } from "./_types";

// Base 4-block recipe schema (no prompts — those are section-specific)
const recipeSchema = [
  "## Example recipe",
  "Name: {dish name}",
  "Region: {region}",
  "Season: {season}",
  "Servings: {n}",
  "Prep time: {time}",
  "Cooking time: {time}",
  "Difficulty: {easy/medium/hard}",
  "Cost: {low/medium/high}",
  "Allergens: {list or none}",
  "Diet: {omnivore/vegetarian/vegan/gluten-free}",
  "",
  "### Ingredients",
  "- {amount} {ingredient}",
  "- {amount} {ingredient}",
  "",
  "### Procedure",
  "1. {step}",
  "2. {step}",
  "3. {step}",
  "",
  "### Service and storage notes",
  "{plating, pairing, storage info}",
].join("\n");

// Section-specific recipe examples
const sectionExamples: Record<string, string> = {
  "Bases, stocks and core": [
    "## Example recipe",
    "Name: Brown chicken stock (fond brun de volaille)",
    "Region: French",
    "Season: all year",
    "Servings: makes 2 L",
    "Prep time: 20 min",
    "Cooking time: 4 h",
    "Difficulty: medium",
    "Cost: low",
    "Allergens: none",
    "Diet: gluten-free, dairy-free",
    "",
    "### Ingredients",
    "- 2 kg chicken bones (wings, backs, necks)",
    "- 1 onion, quartered",
    "- 2 carrots, chopped",
    "- 2 celery stalks, chopped",
    "- 10 black peppercorns",
    "- 2 bay leaves",
    "- Cold water to cover",
    "",
    "### Procedure",
    "1. Roast bones at 200°C for 40 min until deep golden.",
    "2. Transfer to stockpot, cover with cold water.",
    "3. Bring to a gentle simmer — never a boil.",
    "4. Skim impurities for the first 30 min.",
    "5. Add mirepoix and aromatics after 1 hour.",
    "6. Simmer 3 more hours, strain through chinois.",
    "",
    "### Service and storage notes",
    "Use within 5 days refrigerated or freeze in portions. The gelatin from wings gives body. Reduce further for a glace.",
  ].join("\n"),

  "Appetizers": [
    "## Example recipe",
    "Name: Burrata with roasted peppers and basil oil",
    "Region: Italy (Puglia)",
    "Season: summer",
    "Servings: 4",
    "Prep time: 15 min",
    "Cooking time: 10 min",
    "Difficulty: easy",
    "Cost: medium",
    "Allergens: dairy",
    "Diet: vegetarian, gluten-free",
    "",
    "### Ingredients",
    "- 2 burrata (each 125 g)",
    "- 4 mixed roasted peppers (jarred is fine)",
    "- 1 handful fresh basil leaves",
    "- Extra virgin olive oil",
    "- Flaky salt, black pepper",
    "- 1 tsp aged balsamic vinegar",
    "",
    "### Procedure",
    "1. Blend basil with 80 ml olive oil until bright green. Strain.",
    "2. Slice peppers into strips, toss with a little oil.",
    "3. Place burrata on plate, tear open.",
    "4. Arrange peppers around, drizzle basil oil and balsamic.",
    "5. Finish with flaky salt and pepper.",
    "",
    "### Service and storage notes",
    "Serve immediately — burrata weeps if it sits. Pairs well with a crisp Vermentino.",
  ].join("\n"),

  "First courses": [
    "## Example recipe",
    "Name: Cacio e pepe",
    "Region: Italy (Roma)",
    "Season: all year",
    "Servings: 4",
    "Prep time: 5 min",
    "Cooking time: 12 min",
    "Difficulty: medium",
    "Cost: low",
    "Allergens: dairy, gluten",
    "Diet: vegetarian",
    "",
    "### Ingredients",
    "- 320 g tonnarelli or spaghetti",
    "- 200 g Pecorino Romano DOP, finely grated",
    "- 2 tbsp whole black peppercorns",
    "- Salt (for pasta water)",
    "",
    "### Procedure",
    "1. Toast peppercorns in a dry pan, crack coarsely.",
    "2. Boil pasta in well-salted water (1 min less than package).",
    "3. Reserve 500 ml starchy pasta water.",
    "4. In a bowl, mix Pecorino with a ladle of warm (not boiling) water to form a cream.",
    "5. Toss drained pasta in the pepper pan with a splash of water.",
    "6. Off heat, fold in the Pecorino cream, adding pasta water to reach a silky consistency.",
    "",
    "### Service and storage notes",
    "Serve immediately — the starch sets quickly. The key is temperature control: too hot and the cheese clumps.",
  ].join("\n"),

  "Main courses": [
    "## Example recipe",
    "Name: Slow-roasted pork shoulder with fennel and citrus",
    "Region: Italy (Toscana)",
    "Season: autumn/winter",
    "Servings: 6",
    "Prep time: 30 min",
    "Cooking time: 4 h",
    "Difficulty: medium",
    "Cost: medium",
    "Allergens: none",
    "Diet: gluten-free, dairy-free",
    "",
    "### Ingredients",
    "- 1.5 kg pork shoulder, bone-in",
    "- 2 fennel bulbs, quartered",
    "- 2 oranges, zest and juice",
    "- 4 garlic cloves, smashed",
    "- 2 tbsp fennel seeds",
    "- Fresh rosemary, sage",
    "- Olive oil, salt, pepper",
    "",
    "### Procedure",
    "1. Score the pork skin, rub with salt, fennel seeds, garlic, orange zest.",
    "2. Refrigerate uncovered overnight (for crispy skin).",
    "3. Bring to room temperature 1 hour before cooking.",
    "4. Roast at 160°C for 3.5 hours, basting with orange juice every 45 min.",
    "5. Increase to 220°C for the last 30 min to crisp the skin.",
    "6. Rest 20 min before carving.",
    "",
    "### Service and storage notes",
    "Slice thick, serve with roasted fennel and a spoonful of salsa verde. Leftovers make incredible sandwiches.",
  ].join("\n"),

  "Side dishes": [
    "## Example recipe",
    "Name: Crispy roasted potatoes with rosemary and garlic",
    "Region: Italy",
    "Season: all year",
    "Servings: 4",
    "Prep time: 10 min",
    "Cooking time: 45 min",
    "Difficulty: easy",
    "Cost: low",
    "Allergens: none",
    "Diet: vegan, gluten-free",
    "",
    "### Ingredients",
    "- 800 g waxy potatoes (Yukon Gold), cut in chunks",
    "- 4 garlic cloves, crushed",
    "- 3 sprigs fresh rosemary",
    "- Extra virgin olive oil",
    "- Flaky salt",
    "",
    "### Procedure",
    "1. Parboil potatoes in salted water for 8 min. Drain and shake to roughen edges.",
    "2. Toss with olive oil, garlic, rosemary on a baking tray.",
    "3. Roast at 220°C for 40-45 min, turning once.",
    "4. Finish with flaky salt.",
    "",
    "### Service and storage notes",
    "The roughened edges create extra crunch. Serve alongside any roasted meat or fish.",
  ].join("\n"),

  "Desserts": [
    "## Example recipe",
    "Name: Classic tiramisù",
    "Region: Italy (Veneto)",
    "Season: all year",
    "Servings: 8",
    "Prep time: 30 min",
    "Cooking time: 0 min (+ 4 h resting)",
    "Difficulty: medium",
    "Cost: medium",
    "Allergens: dairy, eggs, gluten",
    "Diet: vegetarian",
    "",
    "### Ingredients",
    "- 6 egg yolks",
    "- 150 g sugar",
    "- 500 g mascarpone",
    "- 300 ml heavy cream",
    "- 400 ml strong espresso, cooled",
    "- 300 g savoiardi (ladyfingers)",
    "- Unsweetened cocoa powder",
    "- Dark rum or Marsala (optional)",
    "",
    "### Procedure",
    "1. Whisk yolks with sugar until pale and thick.",
    "2. Fold in mascarpone until smooth.",
    "3. Whip cream to soft peaks, fold into the mascarpone mixture.",
    "4. Briefly dip each savoiardi in espresso (do not soak).",
    "5. Layer: cream → biscuits → cream → biscuits → cream.",
    "6. Dust generously with cocoa. Refrigerate at least 4 hours.",
    "",
    "### Service and storage notes",
    "Best after 12 hours. Keeps 3 days refrigerated. The rum adds depth but is optional.",
  ].join("\n"),

  "Plant-based cooking": [
    "## Example recipe",
    "Name: Chickpea socca with za'atar and lemon",
    "Region: France (Nice) / Middle East",
    "Season: spring/summer",
    "Servings: 4",
    "Prep time: 12 h (soaking) + 10 min",
    "Cooking time: 15 min",
    "Difficulty: easy",
    "Cost: low",
    "Allergens: none",
    "Diet: vegan, gluten-free",
    "",
    "### Ingredients",
    "- 250 g dried chickpeas (soaked overnight)",
    "- 250 ml water",
    "- 3 tbsp olive oil + more for cooking",
    "- 1 tsp salt",
    "- 2 tbsp za'atar",
    "- 1 lemon, zested and juiced",
    "- Fresh herbs (mint, parsley)",
    "",
    "### Procedure",
    "1. Blend soaked chickpeas with water, 3 tbsp oil, and salt until very smooth.",
    "2. Rest batter 30 min at room temperature.",
    "3. Heat a cast-iron skillet with a thin layer of oil.",
    "4. Pour batter (3-4 mm thick), cook 5 min on high heat.",
    "5. Sprinkle with za'atar, flip, cook 3 more min.",
    "6. Finish with lemon zest, juice, fresh herbs.",
    "",
    "### Service and storage notes",
    "Serve hot as a flatbread alternative. The crispy edges are the best part.",
  ].join("\n"),

  "Slow Food Presidia": [
    "## Example recipe",
    "Name: Fagiolo di Sorana al fagiolo",
    "Region: Italy (Toscana, Valleriana)",
    "Season: autumn/winter",
    "Servings: 4",
    "Prep time: 12 h (soaking) + 15 min",
    "Cooking time: 2 h",
    "Difficulty: easy",
    "Cost: medium",
    "Allergens: none",
    "Diet: vegan, gluten-free",
    "",
    "### Ingredients",
    "- 400 g Fagiolo di Sorana (or borlotti as substitute)",
    "- 1 onion, halved",
    "- 2 garlic cloves",
    "- 1 celery stalk",
    "- 1 sprig rosemary",
    "- Extra virgin olive oil",
    "- Salt, black pepper",
    "",
    "### Procedure",
    "1. Soak beans overnight in cold water.",
    "2. Drain, cover with fresh water, add onion, garlic, celery, rosemary.",
    "3. Bring to a gentle simmer — never boil (the skin splits).",
    "4. Cook 1.5-2 hours until creamy inside.",
    "5. Remove aromatics, season with salt and pepper.",
    "6. Serve in a shallow bowl with a generous drizzle of good olive oil.",
    "",
    "### Service and storage notes",
    "The Sorana bean is fragile — handle gently. Its thin skin and creamy texture are what make it a Presidio. Serve as a simple soup or over toasted bread.",
  ].join("\n"),

  "Menu and service": [
    "## Example recipe",
    "Name: 5-course autumn tasting menu",
    "Region: Italy",
    "Season: autumn",
    "Servings: tasting portions",
    "Prep time: varies",
    "Cooking time: varies",
    "Difficulty: hard",
    "Cost: high",
    "Allergens: varies per course",
    "Diet: adaptable",
    "",
    "### Menu structure",
    "1. Amuse-bouche: Burrata bite with roasted pepper and basil oil\n2. First: Cacio e pepe\n3. Fish: Pan-seared sea bass with fennel purée\n4. Main: Slow-roasted pork shoulder with citrus\n5. Dessert: Tiramisù\n\n### Pacing",
    "- Amuse: 5 min\n- First to fish: 15 min gap\n- Fish to main: 20 min gap\n- Main to dessert: 15 min gap\n- Total: ~90 min",
    "",
    "### Allergen summary",
    "Course 1: dairy. Course 2: dairy, gluten. Course 3: fish. Course 4: none. Course 5: dairy, eggs, gluten.",
    "",
    "### Service notes",
    "Pre-portion desserts. Keep tiramisù in the fridge until the last moment. Wine pairing: Vermentino (courses 1-3), Chianti (course 4), Vin Santo (course 5).",
  ].join("\n"),

  "Costs and food cost": [
    "## Example recipe",
    "Name: Food cost calculation — Cacio e pepe",
    "Region: Italy",
    "Season: all year",
    "Servings: 4",
    "Prep time: —",
    "Cooking time: —",
    "Difficulty: easy",
    "Cost: low",
    "Allergens: —",
    "Diet: —",
    "",
    "### Ingredient costs (approximate)",
    "- Tonnarelli 320 g: €1.20\n- Pecorino Romano 200 g: €4.80\n- Pepper: €0.10\n- Salt: €0.05\n- **Total plate cost: €6.15**",
    "",
    "### Pricing",
    "- Food cost target: 28%\n- Menu price: €6.15 / 0.28 = **€22**\n- Actual menu price: **€18** (competitive for the area)\n- Actual food cost: 6.15 / 18 = **34%** (slightly high — consider raising price or reducing Pecorino portion)",
  ].join("\n"),

  "Research and development": [
    "## Example recipe",
    "Name: Book notes — 'The Art of Pasta' by Kate Leahy",
    "Region: Italy",
    "Season: —",
    "Servings: —",
    "Prep time: —",
    "Cooking time: —",
    "Difficulty: —",
    "Cost: —",
    "Allergens: —",
    "Diet: —",
    "",
    "### Key takeaways",
    "- Fresh egg pasta: 100 g flour per 1 large egg is the baseline.",
    "- Pasta al torchio (extruded) needs semolina + water only.",
    "- Resting dough 30 min relaxes gluten — easier to roll.",
    "- Drying: hang only when the pasta is leather-dry, not before.",
    "",
    "### Techniques to try",
    "1. Sfoglia bolognese (thin enough to read a love letter through).\n2. Cacio e pepe technique: the 'cremina' method (mix cheese with a little cold water first, then add starchy water gradually).\n3. Egg yolk raviolo with butter and sage — timing the burst.",
  ].join("\n"),

  "Media": [
    "## Example recipe",
    "Name: Photo styling — autumn plate composition",
    "Region: —",
    "Season: autumn",
    "Servings: —",
    "Prep time: 15 min (styling)",
    "Cooking time: —",
    "Difficulty: easy",
    "Cost: low",
    "Allergens: —",
    "Diet: —",
    "",
    "### Styling checklist",
    "- Background: dark wood or slate (autumn mood).",
    "- Hero plate: white ceramic, slightly oversized.",
    "- Props: linen napkin (muted tones), vintage fork, scattered herbs.",
    "- Lighting: natural side light from a window, diffused with sheer curtain.",
    "- Angle: 45° or overhead for flat plates, 30° for bowls.",
    "",
    "### Caption template",
    "\"{Dish name} — {one sentence about the dish or the ingredient}. {season or occasion context}. #foodphotography #{season}recipe\"",
  ].join("\n"),
};

const chefTutorial = (title: string, intro: string, prompts: string[]) => {
  const example = sectionExamples[title] || recipeSchema;
  return {
    title,
    body: [
      intro,
      "",
      example,
      "",
      "## Suggested prompts",
      ...prompts.map((p) => `- Ask the AI: "${p}"`),
    ].join("\n"),
  };
};

const sectionWithRecipeTutorial = (
  name: string,
  intro: string,
  prompts: string[]
): TemplateSectionSpec => ({
  name,
  tutorial: chefTutorial(name, intro, prompts),
});

const chefAFlatSections: TemplateSectionSpec[] = [
  sectionWithRecipeTutorial("Bases, stocks and core", "Start your recipe book with the foundations: stocks, sauces, doughs, mother preparations. These are the building blocks you will reuse across the menu.", [
    "Generate a base recipe for a classic chicken stock",
    "What is the correct ratio water-to-bones for a brown stock?",
    "Explain the difference between a fond and a jus",
  ]),
  sectionWithRecipeTutorial("Appetizers", "Appetizers open the meal. This section gathers starters, amuse-bouche, small bites and cold plates.", [
    "Suggest 5 seasonal appetizers for autumn",
    "Generate a recipe card for a vegetarian amuse-bouche",
    "What plating works best for a one-bite amuse-bouche?",
  ]),
  sectionWithRecipeTutorial("First courses", "First courses include pasta, rice, soups, gnocchi. Use this section to keep your pasta logic organised by type and cooking method.", [
    "Which pasta shape works best with a thick meat ragù?",
    "Generate a recipe card for a classic Roman carbonara",
    "Suggest a vegetarian first course with seasonal vegetables",
  ]),
  sectionWithRecipeTutorial("Main courses", "Main courses cover meat, fish, vegetarian proteins and eggs. Keep the cooking temperatures and timings documented here.", [
    "Generate a recipe card for a slow-cooked beef brisket",
    "What is the safe internal temperature for a medium-rare beef tenderloin?",
    "Suggest a vegetarian main course for a winter menu",
  ]),
  sectionWithRecipeTutorial("Side dishes", "Side dishes complete the plate: vegetables, grains, salads. Use this section to keep your pairings documented.", [
    "Suggest 3 side dishes that pair with grilled salmon",
    "Generate a recipe for a classic Italian contorno",
    "Which side dishes work for a vegan tasting menu?",
  ]),
  sectionWithRecipeTutorial("Desserts", "Desserts: cakes, pastry, ice cream, fruit-based sweets. Document the bases (creams, doughs) and the plated desserts here.", [
    "Generate a recipe card for a classic tiramisù",
    "What is the safe temperature for sugar syrup stages?",
    "Suggest a gluten-free dessert for a summer menu",
  ]),
  sectionWithRecipeTutorial("Plant-based cooking", "Plant-based cooking: proteins from legumes, grains, vegetables. Document substitutions, techniques and flavour pairings.", [
    "Generate a recipe for a plant-based protein using chickpeas",
    "Which legumes are richest in protein?",
    "Suggest a plant-based substitute for traditional beef stock",
  ]),
  sectionWithRecipeTutorial("Slow Food Presidia", "Slow Food Presidia protect traditional products at risk of extinction. Use this section to keep recipes and notes about ingredients tied to a Presidio.", [
    "Which Slow Food Presidia exist in Piedmont?",
    "Generate a recipe card featuring a Slow Food Presidio ingredient",
    "How do I substitute a Presidio ingredient if I cannot source it?",
  ]),
  sectionWithRecipeTutorial("Menu and service", "Use this section to design complete menus (seasonal, tasting, à la carte) and to keep service notes: pacing, plating, allergens per dish.", [
    "Draft a 5-course autumn tasting menu",
    "Which allergens must I declare for this menu?",
    "What is a balanced pacing between courses?",
  ]),
  sectionWithRecipeTutorial("Costs and food cost", "Track ingredient costs, plate cost, margins. Use this section to keep your food cost spreadsheets and per-dish calculations.", [
    "Calculate the food cost of {recipe}",
    "What is a healthy food cost target for a mid-range restaurant?",
    "Which ingredient in this recipe is the most expensive?",
  ]),
  sectionWithRecipeTutorial("Research and development", "Document books, chefs, techniques and food science you study. The AI uses this to suggest new ideas and answer technical questions.", [
    "Recommend a book on modern Italian pastry",
    "What is the Maillard reaction and how does it affect roasting?",
    "Which chef is known for {technique}?",
  ]),
  sectionWithRecipeTutorial("Media", "Photo styling, video reels, social media content. Use this section to keep your visual identity guidelines and caption templates.", [
    "Suggest a caption for a {dish} photo",
    "What is the best lighting for food photography at home?",
    "Draft a 30-second reel script for a recipe",
  ]),
];

const chefBLeafSection = (
  name: string,
  intro: string,
  prompts: string[]
): TemplateSectionSpec => ({
  name,
  tutorial: chefTutorial(name, intro, prompts),
});

const chefBMultibranchSections: TemplateSectionSpec[] = [
  {
    name: "01 Bases, stocks and core",
    children: [
      chefBLeafSection("Stocks and broths", "Document your classic stocks (white, brown, fish, vegetable) with ratios, timings and uses.", [
        "Generate a brown beef stock recipe",
        "What is the correct ratio bones-to-water for a white stock?",
        "When should I use a fish stock vs a vegetable stock?",
      ]),
      chefBLeafSection("Mother sauces", "The five French mother sauces (béchamel, velouté, espagnole, hollandaise, tomate) and their derivatives.", [
        "Generate a béchamel recipe and list 3 derivatives",
        "What is the difference between velouté and espagnole?",
        "How do I fix a broken hollandaise?",
      ]),
      chefBLeafSection("Base doughs", "Pasta dough, pizza dough, bread dough, shortcrust, puff, choux. Document ratios and hydration.", [
        "Generate a fresh egg pasta dough recipe",
        "What is the correct hydration for a pizza dough?",
        "How do I keep puff pastry cold while laminating?",
      ]),
      chefBLeafSection("HACCP standards", "Storage temperatures, FIFO, cross-contamination, personal hygiene, cleaning schedules. Reference the Italian and EU HACCP rules.", [
        "What is the safe storage temperature for fresh fish?",
        "Draft a HACCP plan for a small restaurant",
        "What is FIFO and how do I implement it?",
      ]),
    ],
  },
  {
    name: "02 Geography and territory",
    children: [
      {
        name: "Italian regional",
        children: [
          chefBLeafSection("Northern Italy", "Piedmont, Lombardy, Emilia-Romagna, Veneto, Liguria. Risotto, polenta, butter-based sauces, cured meats, aged cheeses.", [
            "Generate a recipe typical of Piedmont",
            "What distinguishes Emilian cuisine from Lombard cuisine?",
            "List 5 DOP ingredients from Northern Italy",
          ]),
          chefBLeafSection("Central Italy", "Tuscany, Lazio, Umbria, Marche. Olive oil, grilled meats, hearty soups, porchetta, strangozzi.", [
            "Generate a classic Tuscan ribollita recipe",
            "What is the difference between strangozzi and pappardelle?",
            "Describe a traditional Umbrian sagra",
          ]),
          chefBLeafSection("Southern Italy", "Campania, Calabria, Puglia, Basilicata. Tomatoes, olive oil, dried pasta, seafood, nduja, burrata.", [
            "Generate a recipe for orecchiette con cime di rapa",
            "What makes San Marzano tomatoes special?",
            "Suggest 3 Puglian antipasti",
          ]),
          chefBLeafSection("Islands", "Sicily, Sardinia. Couscous, bottarga, pecorino sardo, pasta alla Norma, malloreddus.", [
            "Generate a recipe for pasta alla Norma",
            "What is bottarga and how is it used?",
            "Describe a traditional Sardinian festival dish",
          ]),
        ],
      },
      {
        name: "International",
        children: [
          chefBLeafSection("Europe", "France, Spain, Greece, Scandinavia. Classical technique, tapas, meze, New Nordic.", [
            "Compare French and Italian approaches to sauce-making",
            "Generate a Spanish tapas recipe",
            "What is the New Nordic philosophy?",
          ]),
          chefBLeafSection("Asia", "Japan, China, Thailand, India. Umami, wok technique, fermentation, spice balancing.", [
            "Explain the concept of umami in Japanese cuisine",
            "Generate a Thai curry paste recipe",
            "What is the wok hei and how do I achieve it?",
          ]),
          chefBLeafSection("Americas", "Mexico, Peru, USA (South), Brazil. Chiles, corn, ceviche, barbecue, feijoada.", [
            "Generate a Peruvian ceviche recipe",
            "What is the difference between Mexican and Tex-Mex?",
            "Explain the science of barbecue smoking",
          ]),
          chefBLeafSection("Africa", "North Africa, West Africa, Ethiopia. Tagines, injera, harissa, jollof, berbere.", [
            "Generate a Moroccan tagine recipe",
            "What is injera and how is it made?",
            "Describe the flavour profile of berbere spice blend",
          ]),
          chefBLeafSection("Middle East", "Lebanon, Turkey, Iran, Israel. Mezze, kebabs, flatbreads, labneh, za'atar.", [
            "Generate a Lebanese mezze platter",
            "What is za'atar and how do I use it?",
            "Compare Turkish and Iranian kebab traditions",
          ]),
        ],
      },
    ],
  },
  {
    name: "03 Traditional courses",
    children: [
      {
        name: "Appetizers",
        children: [
          chefBLeafSection("Cold plates", "Crudo, tartare, carpaccio, salads, ceviche. Temperature control, knife work, acid balance.", [
            "Generate a beef carpaccio recipe with truffle oil",
            "How do I keep avocado from browning in a cold plate?",
            "What is the ideal temperature for serving crudo?",
          ]),
          chefBLeafSection("Hot starters", "Fritti, crostini, arancini, tempura. Batter formulas, oil temperature, draining.", [
            "Generate an arancini recipe with ragù filling",
            "What oil temperature for perfect tempura?",
            "How do I keep fritti crispy after frying?",
          ]),
        ],
      },
      {
        name: "First courses",
        children: [
          chefBLeafSection("Dry pasta", "Spaghetti, penne, rigatoni. Cooking times, sauce pairing by shape, al dente.", [
            "Which pasta shape pairs best with pesto?",
            "Generate a recipe for Amatriciana",
            "How do I cook pasta al dente consistently?",
          ]),
          chefBLeafSection("Fresh pasta", "Tagliatelle, pappardelle, ravioli, tortellini. Egg ratios, rolling thickness, filling balance.", [
            "Generate a ravioli recipe with ricotta and spinach",
            "What is the correct egg-to-flour ratio for fresh pasta?",
            "How thin should I roll pasta for tortellini?",
          ]),
          chefBLeafSection("Stuffed pasta", "Ravioli, tortellini, agnolotti, cappelletti. Folding techniques, filling moisture control.", [
            "Generate a tortellini in brodo recipe",
            "How do I prevent stuffed pasta from opening during cooking?",
            "What filling combinations work for agnolotti?",
          ]),
          chefBLeafSection("Rice and risotto", "Carnaroli, arborio, vialone nano. Toasting, deglazing, mantecatura, broth temperature.", [
            "Generate a classic Milanese risotto recipe",
            "What is mantecatura and why does it matter?",
            "Which rice variety is best for seafood risotto?",
          ]),
          chefBLeafSection("Soups", "Minestrone, ribollita, broth-based, cream soups. Layering flavour, vegetable prep, finishing.", [
            "Generate a Tuscan ribollita recipe",
            "How do I build flavour in a vegetable soup?",
            "What is the difference between a velouté and a cream soup?",
          ]),
          chefBLeafSection("Gnocchi", "Potato gnocchi, ricotta gnocchi, gnocchi alla romana. Weight, moisture, cooking method.", [
            "Generate a potato gnocchi recipe",
            "How do I prevent gnocchi from being dense?",
            "What sauce works best with ricotta gnocchi?",
          ]),
          chefBLeafSection("Baked pasta", "Lasagne, pasticcio, cannelloni. Béchamel ratios, layering, baking time.", [
            "Generate a classic lasagne al forno recipe",
            "How many layers for a perfect lasagne?",
            "What temperature and time for baking pasticcio?",
          ]),
        ],
      },
      {
        name: "Main courses",
        children: [
          chefBLeafSection("Meat", "Beef, pork, lamb, poultry. Temperatures, resting times, brining, marinades.", [
            "Generate a recipe for ossobuco alla milanese",
            "What is the safe internal temperature for pork tenderloin?",
            "How long should I rest a roast beef?",
          ]),
          chefBLeafSection("Fish and seafood", "Whole fish, fillets, shellfish, crustaceans. Cleaning, skin crisping, sauce pairing.", [
            "Generate a whole sea bass al forno recipe",
            "How do I get crispy skin on a fish fillet?",
            "What is the correct way to clean a squid?",
          ]),
          chefBLeafSection("Vegetarian proteins", "Tofu, tempeh, legume-based, egg-based. Pressing, marinating, texture development.", [
            "Generate a crispy tofu recipe with Asian glaze",
            "How do I press tofu properly?",
            "What makes a good bean burger that doesn't fall apart?",
          ]),
          chefBLeafSection("Eggs", "Frittata, quiche, soufflé, poached, scrambled. Temperature control, timing, seasoning.", [
            "Generate a classic Italian frittata recipe",
            "How do I poach an egg perfectly?",
            "What is the secret to creamy scrambled eggs?",
          ]),
        ],
      },
      {
        name: "Side dishes",
        children: [
          chefBLeafSection("Vegetables", "Roasting, grilling, steaming, raw. Seasonality, colour, texture contrast.", [
            "Generate a recipe for roasted Mediterranean vegetables",
            "How do I keep green vegetables vibrant when cooking?",
            "What is the best way to grill summer squash?",
          ]),
          chefBLeafSection("Grains and legumes", "Risotto, polenta, farro, chickpeas, lentils. Cooking methods, flavour absorption.", [
            "Generate a farro salad recipe",
            "How do I cook polenta until smooth and creamy?",
            "What is the best grain for a warm winter salad?",
          ]),
        ],
      },
      {
        name: "Desserts",
        children: [
          chefBLeafSection("Cakes and tarts", "Sponge, cheesecake, crostata, torte. Flour types, leavening, baking temperatures.", [
            "Generate a recipe for a classic crostata di marmellata",
            "What is the difference between a cake and a torte?",
            "How do I prevent a cheesecake from cracking?",
          ]),
          chefBLeafSection("Pastry", "Puff, shortcrust, choux, filo. Lamination, blind baking, egg wash.", [
            "Generate a choux pastry recipe for profiteroles",
            "How do I blind bake a tart shell?",
            "What is the key to flaky puff pastry?",
          ]),
          chefBLeafSection("Ice cream and frozen", "Gelato, sorbet, semifreddo, granita. Churning, stabiliser ratios, serving temperature.", [
            "Generate a classic fior di latte gelato recipe",
            "What is the difference between gelato and ice cream?",
            "How do I prevent ice crystals in sorbet?",
          ]),
          chefBLeafSection("Plated desserts", "Composition, sauce work, texture contrast, temperature play.", [
            "Design a plated dessert using chocolate and citrus",
            "What is the ideal sauce-to-component ratio on a plate?",
            "How do I create texture contrast in a dessert?",
          ]),
        ],
      },
    ],
  },
  {
    name: "04 Philosophies and special diets",
    children: [
      chefBLeafSection("Plant-based", "Vegan adaptations of classic dishes, plant-based proteins, umami without dairy or meat.", [
        "How do I make a vegan risotto without butter or Parmesan?",
        "What plant-based ingredients provide umami?",
        "Generate a vegan dessert that doesn't feel like a compromise",
      ]),
      chefBLeafSection("Gluten-free", "Gluten-free flours, pasta alternatives, thickening agents, cross-contamination.", [
        "What gluten-free flour blend works best for pasta?",
        "How do I thicken a sauce without flour?",
        "Generate a gluten-free bread recipe",
      ]),
      chefBLeafSection("No added sugar", "Natural sweeteners, fruit-based desserts, reducing sugar in classic recipes.", [
        "How do I sweeten a dessert without refined sugar?",
        "Generate a no-added-sugar fruit sorbet",
        "What happens when I reduce sugar in a cake recipe?",
      ]),
      chefBLeafSection("Low sodium", "Salt alternatives, acid and spice to compensate, naturally flavoured broths.", [
        "How do I reduce sodium without losing flavour?",
        "What herbs and spices compensate for less salt?",
        "Generate a low-sodium vegetable broth",
      ]),
      chefBLeafSection("Slow Food Presidia", "Traditional Italian products at risk: what they are, why they matter, how to source them.", [
        "List 5 Slow Food Presidia from Southern Italy",
        "How do I source Presidio ingredients outside Italy?",
        "Generate a recipe featuring a Presidio tomato variety",
      ]),
    ],
  },
  {
    name: "05 Menu and service",
    children: [
      chefBLeafSection("Seasonal menus", "Designing menus around what is in season. Market-driven cooking, quarterly rotations.", [
        "Design a 4-course spring menu using only seasonal ingredients",
        "What is in season in Italy in October?",
        "How often should I rotate a restaurant menu?",
      ]),
      chefBLeafSection("Wine list", "Pairing principles, regional matches, by-the-glass strategy, non-alcoholic options.", [
        "What wine pairs with a seafood risotto?",
        "Design a wine list for a 5-course tasting menu",
        "Suggest 3 non-alcoholic pairings for an autumn menu",
      ]),
      chefBLeafSection("Allergens", "EU allergen declarations, cross-contamination prevention, menu labelling.", [
        "List the 14 EU allergens I must declare",
        "How do I prevent cross-contamination in a kitchen?",
        "Draft allergen labels for a 3-course menu",
      ]),
      chefBLeafSection("Service rules", "Plating timing, course pacing, table-side service, guest communication.", [
        "What is the correct order for serving a multi-course meal?",
        "How do I handle a guest who sends back a dish?",
        "Describe proper table-side flambé technique",
      ]),
    ],
  },
  {
    name: "06 Costs and food cost",
    children: [
      chefBLeafSection("Calculators", "Food cost formulas, portion cost, break-even, contribution margin.", [
        "Calculate the food cost of a dish with €8 ingredient cost at 30% target",
        "What is the formula for contribution margin?",
        "How do I calculate portion cost from bulk ingredients?",
      ]),
      chefBLeafSection("Margins", "Gross margin, net margin, pricing strategy, discounting.", [
        "What gross margin should a casual restaurant target?",
        "How do I price a new dish for maximum profit?",
        "When is a discount strategy profitable?",
      ]),
      chefBLeafSection("Shopping list", "Ordering quantities, supplier comparison, seasonal pricing, waste reduction.", [
        "Generate a weekly shopping list for a 30-cover restaurant",
        "How do I reduce food waste in ordering?",
        "What is the par level system?",
      ]),
      chefBLeafSection("Reports", "Weekly food cost reports, waste tracking, sales mix analysis.", [
        "Draft a weekly food cost report template",
        "How do I track waste effectively?",
        "What is a sales mix analysis?",
      ]),
    ],
  },
  {
    name: "07 Research and development",
    children: [
      chefBLeafSection("Books", "Cookbooks, food science, technique manuals. Key takeaways and recipes to try.", [
        "Recommend 5 essential Italian cookbooks",
        "What food science book should every chef read?",
        "Summarise the key techniques from 'The Food Lab'",
      ]),
      chefBLeafSection("Restaurants", "Dishes tasted, techniques observed, plating ideas, service notes.", [
        "How do I take useful tasting notes at a restaurant?",
        "What should I look for when dining out for research?",
        "Create a restaurant research template",
      ]),
      chefBLeafSection("Seasonality", "Ingredient calendars, preservation techniques, fermentation schedules.", [
        "Create a month-by-month Italian ingredient calendar",
        "What are the best preservation techniques for summer produce?",
        "How do I plan a menu around a single ingredient's peak season?",
      ]),
      chefBLeafSection("Pairings", "Flavour affinities, wine pairings, unexpected combinations.", [
        "Suggest 3 unexpected flavour pairings for chocolate",
        "What wine pairs with mushroom-based dishes?",
        "How do I build a tasting menu around a single flavour bridge?",
      ]),
    ],
  },
  {
    name: "08 Media",
    children: [
      chefBLeafSection("Dish photography", "Lighting, composition, props, angles for finished plates.", [
        "What is the best natural light for food photography?",
        "How do I style a pasta dish for Instagram?",
        "What camera angle works best for a burger?",
      ]),
      chefBLeafSection("Raw ingredient photography", "Market shots, prep scenes, ingredient close-ups.", [
        "How do I photograph fresh produce at the market?",
        "What makes a good overhead shot of raw ingredients?",
        "Suggest a colour palette for autumn ingredient photography",
      ]),
      chefBLeafSection("Plating", "Plate selection, sauce work, garnish, negative space, colour.", [
        "Describe the rules of plating a fine-dining main course",
        "How do I use negative space on a plate?",
        "What garnishes are functional, not just decorative?",
      ]),
      chefBLeafSection("Events", "Pop-up dinners, cooking classes, food festivals. Planning, budgeting, promotion.", [
        "How do I plan a pop-up dinner from concept to execution?",
        "What is the ideal class size for a cooking workshop?",
        "Draft a social media post for a food festival appearance",
      ]),
    ],
  },
];

// ============================================================================
// ENTITY TYPES
// ============================================================================

const chefEntityTypes: TemplateEntityTypeSpec[] = [
  {
    name: "Recipe",
    icon: "🍲",
    color: "#e67e22",
    fields: [
      { name: "name", type: "text", required: true },
      { name: "category", type: "enum", enum_values: ["appetizer", "first", "main", "side", "dessert", "base", "drink"] },
      { name: "region", type: "text" },
      { name: "season", type: "enum", enum_values: ["spring", "summer", "autumn", "winter", "all year"] },
      { name: "servings", type: "number" },
      { name: "prepTimeMin", type: "number" },
      { name: "cookTimeMin", type: "number" },
      { name: "restTimeMin", type: "number" },
      { name: "difficulty", type: "enum", enum_values: ["easy", "medium", "hard"] },
      { name: "cost", type: "enum", enum_values: ["low", "medium", "high"] },
      { name: "allergens", type: "text", note: "Comma-separated" },
      { name: "diet", type: "enum", enum_values: ["omnivore", "vegetarian", "vegan", "gluten-free", "dairy-free"] },
      { name: "ingredients", type: "text" },
      { name: "procedure", type: "text" },
      { name: "serviceNotes", type: "text" },
    ],
  },
  {
    name: "Ingredient",
    icon: "🥬",
    color: "#27ae60",
    fields: [
      { name: "name", type: "text", required: true },
      { name: "category", type: "enum", enum_values: ["vegetable", "fruit", "meat", "fish", "dairy", "grain", "spice", "condiment", "legume", "nut"] },
      { name: "season", type: "text" },
      { name: "origin", type: "text" },
      { name: "storage", type: "text" },
      { name: "allergens", type: "text" },
      { name: "pairsWith", type: "text", note: "Comma-separated ingredients" },
    ],
  },
  {
    name: "Equipment",
    icon: "🔧",
    color: "#7f8c8d",
    fields: [
      { name: "name", type: "text", required: true },
      { name: "category", type: "enum", enum_values: ["oven", "stove", "tool", "appliance", "smallwares", "storage"] },
      { name: "brand", type: "text" },
      { name: "capacity", type: "text" },
      { name: "notes", type: "text" },
    ],
  },
  {
    name: "Supplier",
    icon: "🚚",
    color: "#3498db",
    fields: [
      { name: "name", type: "text", required: true },
      { name: "category", type: "enum", enum_values: ["produce", "meat", "fish", "dairy", "dry goods", "specialty", "wine"] },
      { name: "location", type: "text" },
      { name: "deliveryDays", type: "text" },
      { name: "minimumOrder", type: "text" },
      { name: "notes", type: "text" },
    ],
  },
  {
    name: "MenuItem",
    icon: "📋",
    color: "#9b59b6",
    fields: [
      { name: "name", type: "text", required: true },
      { name: "recipeId", type: "text", note: "Reference to Recipe entity" },
      { name: "menuPrice", type: "number" },
      { name: "portionCost", type: "number" },
      { name: "foodCostPercent", type: "number" },
      { name: "available", type: "boolean" },
      { name: "season", type: "text" },
      { name: "notes", type: "text" },
    ],
  },
  {
    name: "RecipeVariation",
    icon: "🔀",
    color: "#e74c3c",
    fields: [
      { name: "name", type: "text", required: true },
      { name: "baseRecipeId", type: "text", note: "Reference to Recipe entity" },
      { name: "changes", type: "text", note: "What is different from the base recipe" },
      { name: "reason", type: "text", note: "Dietary, seasonal, cost, or creative reason" },
      { name: "season", type: "text" },
    ],
  },
];

// ============================================================================
// STYLES
// ============================================================================

const chefStyles: { name: string; fragment: string }[] = [
  { name: "Technical-scientific", fragment: "Objective, precise, exact weights, precise timings, specific temperatures. For professional technical sheets, HACCP manuals, food cost reports." },
  { name: "Narrative-traditional", fragment: "Tells the story of the dish, the geographic origins, the family traditions. More discursive sentences, evocation of memories, cultural references. For cookbooks, personal blogs, storytelling." },
  { name: "Inspired by a great chef", fragment: "Inspired by a great chef (e.g. Marchesi, Cracco, Bottura, Bencini, Locatelli, Ramsay). Technical-accessible language, references to innovative techniques, personal vision." },
  { name: "Modern cookbook", fragment: "Contemporary high-end cookbook style. Short sentences, visual pacing, focus on technique and precision. For the reader who wants to understand and replicate." },
  { name: "Family tradition", fragment: "Warm, affectionate, personal anecdotes and memories. Oral transmission from mother to child. For family recipe books, regional traditions, culinary memoirs." },
  { name: "Custom", fragment: "" },
  { name: "User", fragment: "Adapt to the user's personal writing style. Observe the existing text and match its tone, rhythm and vocabulary." },
  { name: "None", fragment: "" },
];

const chefPrompts = {
  suggestions: "You are a professional kitchen assistant. Read the current document and the project structure. Suggest up to 5 brief continuations (1-2 sentences each) for the next step of the recipe or procedure. Respect the chosen writing style.",
  chat: "You are a culinary assistant specialised in Italian and international cuisine. Help the user generate complete recipe cards (4 blocks: metadata, ingredients, procedure, service and storage), scale servings (preserving ratios), calculate food cost, suggest pairings, propose substitutions and recipe variations, and revise recipes technically. Always use the 4-block schema for new recipes. Respect the chosen writing style.",
};

export const chefTemplate: Template = {
  type: "chef",
  displayName: "Chef",
  icon: "🍳",
  description: "For chefs and cooking enthusiasts. Modular recipe book with portion scaling, food cost and classification by course, geography or cooking philosophy.",
  requiresStyleChoice: true,
  sections: chefAFlatSections,
  entityTypes: chefEntityTypes,
  styles: chefStyles,
  defaultStyleName: "Technical-scientific",
  prompts: chefPrompts,
  chefVariant: "a",
};

export const chefTemplateBMultibranch: Template = {
  ...chefTemplate,
  displayName: "Chef (multibranch)",
  chefVariant: "b",
  sections: chefBMultibranchSections,
};
